### ISSUE TITLE
segfault on examples

### ISSUE THREAD

**Issue by jvwilliams23** [aurora-multiphysics/VacuumMesher#18]
Hi,

I am running into seg faults when running the vacuum example 

```
[scarf1324@cn1052 oldcommitVacuumMesher]$ ./build/bin/vacuum -v -i Examples/example_mesh.e -o example_vac.e --bound_len 2
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind and https://petsc.org/release/faq/
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run
[0]PETSC ERROR: to get more information on the crash.
[0]PETSC ERROR: Run with -malloc_debug to check if memory corruption is causing the crash.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 59.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

I have tried on the latest commit and also an older one (9123320c144982fa3df9db620e6a3694cbb983e3). 

Sometimes it works fine, sometimes it gives the above error. On the mesh I am trying to build the vacuum for (much larger than the example), it gives this error every time.

I am using the following configuration:
- libmesh commit b2248b5 (https://github.com/libMesh/libmesh/commit/b2248b506847fd72d37cff56b6f4d8432f6c7e92)
- petsc commit 38aca50 (https://github.com/petsc/petsc/commit/38aca504f6ea08cc814f159b2c9bcf837a5876f3)

**Comment by TheBEllis** [comment]
I believe the segfault should be fixed by the linked PR.

**Comment by jvwilliams23** [comment]
Hi @TheBEllis, thanks for looking into this. 
It seems to still get segfault sometimes on example_mesh.e, and all the time on bigger meshes (e.g. CHIMERA).

**Comment by TheBEllis** [comment]
No worries @jvwilliams23, sorry it took so long to get round to it. The example from the original issue seems to be working for me on main, I will try with the libmesh commit you're using

**Comment by jvwilliams23** [comment]
No worries. I will try the latest libmesh

**Comment by jvwilliams23** [comment]
Still get it when running with recent libmesh (https://github.com/libMesh/libmesh/commit/5483644b60cc538a4b54d312f28835bd94107627).

What compiler stack are you using? I have GCC 11.2 and OpenMPI 4.1.1 (compiled with GCC 11.2)

**Comment by jvwilliams23** [comment]
Hi @TheBEllis. 
I tested on another machine, still get this error on the example.

**Comment by jvwilliams23** [comment]
Here is the output from gdb:

```
Starting program: /netfs/smain01/scafellpike/local/HT04544/sht09/jxw92-sht09/VacuumMesher/./build/bin/vacuum -v -i Examples/example_mesh.e --bound_len 2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[Detaching after fork from child process 9712]
[New Thread 0x2aaab8ea8700 (LWP 9720)]
[New Thread 0x2aaab926e700 (LWP 9724)]
[New Thread 0x2aaabb7bc700 (LWP 9725)]

Program received signal SIGSEGV, Segmentation fault.
0x00002aaaaab225c5 in SurfaceMeshGenerator::getFaceInfo(libMesh::Elem*, int&, std::vector<int, std::allocator<int> >&, std::vector<int, std::allocator<int> >&, std::map<int, std::vector<short, std::allocator<short> >, std::less<int>, std::allocator<std::pair<int const, std::vector<short, std::allocator<short> > > > >&) ()
   from /lustre/scafellpike/local/HT04544/sht09/jxw92-sht09/VacuumMesher/build/VacuumMeshing/libvmesh_opt.so
```

**Comment by jvwilliams23** [comment]
Now when I link VacuumMesher to libmesh dbg libraries, it gives this:

```
#0  0x00002aaaaae7d3a8 in libMesh::DofObject::id (this=0x3100000043)
    at /lustre/scafellpike/local/HT04544/sht09/jxw92-sht09/jvwilliams23_moose/libmesh/installed/include/libmesh/dof_object.h:828
No locals.
#1  0x00002aaaaae9dce3 in SurfaceMeshGenerator::getFaceInfo (this=0x7fffffff93e0, elem=0xaf7fb0, face_id=@0xacd9f0: 2, original_node_ids=..., connectivity=..., boundary_data=...)
    at /lustre/scafellpike/local/HT04544/sht09/jxw92-sht09/VacuumMesher/VacuumMeshing/src/SurfaceMeshing/SurfaceGenerator.cpp:360
        global_node_id = 16
        side_node = @0x310000002b: <error reading variable>
        __for_range = <unknown type in /lustre/scafellpike/local/HT04544/sht09/jxw92-sht09/VacuumMesher/build/VacuumMeshing/libvmesh_dbg.so, CU 0x25ddb6, DIE 0x2df804>
        __for_begin = {<libMesh::PointerToPointerIter<libMesh::Node>> = {_it = 0xa82f28}, <No data fields>}
        __for_end = {<libMesh::PointerToPointerIter<libMesh::Node>> = {_it = 0xa82f30}, <No data fields>}
        boundary_ids = {<std::_Vector_base<short, std::allocator<short> >> = {
            _M_impl = {<std::allocator<short>> = {<__gnu_cxx::new_allocator<short>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<short, std::allocator<short> >::_Vector_impl_data> = {_M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}, <No data fields>}}, <No data fields>}
```

seems to be a problem with `side_node` in getFaceInfo

**Comment by jvwilliams23** [comment]
Seems to go away when running with docker. Must be an issue with libmesh configuration (I was using standard MOOSE/libmesh config)
